server:
  port: ${PORT:8000}

spring:
  main.web-application-type: none

  application:

    name: time-bot

  datasource:

    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/bot_db}
    username: ${JDBC_DATABASE_USERNAME:bot_user}
    password: ${JDBC_DATABASE_PASSWORD:bot_pass}
    type: com.zaxxer.hikari.HikariDataSource
    platform: postgresql

    hikari:

      connection-test-query: SELECT 1
      minimum-idle: ${DB_IDLE_CONN:1}
      maximum-pool-size: ${DB_POOL_SIZE:5}
      pool-name: bot-pool

  flyway:

    group: true
    locations: ${DB_MIGRATIONS_PATH:classpath:/db/migrations,filesystem:migrations,classpath:db/migration}
    baselineOnMigrate: true

telegram-bot:
  admin-user: ${BOT_ADMIN_ID:1604685}
  token: ${BOT_TOKEN:""}
  poll-time: ${BOT_POLL_TIME:100}